version: '3'

services:
  rs-portfolio:
    image: node:14.9.0-alpine3.10
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    expose:
      - 3000
    command: >
      sh -c 'npm rebuild node-sass && npm run dev'
